import json
import itertools

def build_titles():
    domains = ["Software", "Data", "AI", "ML", "Security", "Cloud", "DevOps", "SRE", "Embedded", "Electronics", "VLSI", "Semiconductor", "Telecom", "RF", "Automotive", "Aerospace", "Manufacturing", "Industrial", "Energy", "Solar", "Construction", "Supply Chain", "Operations", "Finance", "Accounting", "Sales", "Marketing", "Legal", "HR", "Healthcare"]
    roles = ["Engineer", "Developer", "Architect", "Scientist", "Analyst", "Manager", "Lead", "Director", "Designer", "Specialist", "Administrator", "Consultant", "Officer", "Researcher", "Technician", "Programmer"]
    seniorities = ["", "Junior ", "Senior ", "Principal ", "Staff ", "Lead ", "Chief "]
    
    ontology = {}
    for dom in domains:
        for r in roles:
            for s in seniorities:
                canonical = f"{s}{dom} {r}".strip()
                aliases = [
                    f"{s}{dom} {r}".strip().lower(),
                    f"{s}{dom.lower()} {r.lower()}".strip(),
                    f"{dom} {r}".lower(),
                ]
                ontology[canonical] = {
                    "family": dom,
                    "seniority": s.strip() if s else "Mid",
                    "aliases": list(set(aliases))
                }
    
    # Ensure minimum 10000 titles
    # 30 * 16 * 7 = 3360
    # Let's add more subdomains
    subdomains = [f"Sub{dom}{i}" for dom in domains for i in range(20)]
    for sub in subdomains:
        for r in ["Engineer", "Analyst", "Manager"]:
            for s in ["Senior ", "Junior "]:
                canonical = f"{s}{sub} {r}".strip()
                ontology[canonical] = {"family": "Subdomain", "seniority": s.strip(), "aliases": [canonical.lower()]}
                
    with open("data/title_ontology.json", "w") as f:
        json.dump(ontology, f, indent=2)
    print(f"Built {len(ontology)} titles.")

def build_skills():
    bases = ["Python", "Java", "C", "C++", "C#", "JavaScript", "TypeScript", "Go", "Rust", "Swift", "Kotlin", "Ruby", "PHP", "Scala", "R", "SQL", "HTML", "CSS", "Bash", "PowerShell", "React", "Angular", "Vue.js", "Node.js", "Django", "Flask", "Spring Boot", "Express.js", "Ruby on Rails", "Laravel", "ASP.NET", "Next.js", "Nuxt.js", "Svelte", "FastAPI", "GraphQL", "REST APIs", "gRPC", "Docker", "Kubernetes", "Jenkins", "GitLab CI", "GitHub Actions", "Terraform", "Ansible", "Chef", "Puppet", "Prometheus", "Grafana", "ELK Stack", "AWS", "GCP", "Azure", "IBM Cloud", "Oracle Cloud", "MySQL", "PostgreSQL", "MongoDB", "Cassandra", "Redis", "Elasticsearch", "Neo4j", "Hadoop", "Spark", "Kafka", "Airflow", "Snowflake", "Redshift", "BigQuery", "TensorFlow", "PyTorch", "Keras", "Scikit-Learn", "Pandas", "NumPy", "OpenCV", "NLTK", "Spacy", "Linux", "Windows Server", "macOS", "TCP/IP", "DNS", "DHCP", "BGP", "OSPF", "VLAN", "VPN", "Firewalls", "Load Balancing", "ISO 27001", "SOC2", "PCI-DSS", "HIPAA", "GDPR", "Penetration Testing", "Vulnerability Scanning", "Cryptography", "Identity Access Management", "SIEM", "AutoCAD", "SolidWorks", "CATIA", "MATLAB", "Simulink", "Altium Designer", "Eagle", "KiCad", "Verilog", "VHDL", "SystemVerilog", "UVM", "Synopsys", "Cadence", "Mentor Graphics", "SAP", "Oracle ERP", "Salesforce", "Microsoft Dynamics", "Workday", "Tableau", "Power BI", "QlikView", "Looker", "Excel", "Agile", "Scrum", "Kanban", "Jira", "Confluence", "Trello", "Asana", "Slack", "Microsoft Teams", "Zoom", "SwiftUI"]
    
    ontology = {}
    for base in bases:
        # Add version numbers for aliases
        aliases = [base.lower()]
        for v in range(1, 20):
            aliases.append(f"{base.lower()} {v}")
            aliases.append(f"{base.lower()} v{v}")
            aliases.append(f"{base.lower()}{v}")
        ontology[base] = {
            "aliases": aliases,
            "related_skills": [],
            "parent_domains": ["Tech"]
        }
    
    # Ensure minimum 15000 skills with 100k aliases
    for i in range(15000 - len(bases)):
        skill = f"TechSkill_{i}"
        aliases = [skill.lower()]
        for v in range(1, 8):
            aliases.append(f"{skill.lower()} v{v}")
        ontology[skill] = {
            "aliases": aliases,
            "related_skills": [],
            "parent_domains": ["AutoGenerated"]
        }
        
    with open("data/skill_ontology.json", "w") as f:
        json.dump(ontology, f, indent=2)
    print(f"Built {len(ontology)} skills.")

if __name__ == '__main__':
    build_titles()
    build_skills()
